### ISSUE TITLE
Filtering by endpoint paths or tags?

### ISSUE THREAD

**Issue by er1c** [ghostbuster91/sttp-openapi-generator#46]
Original source: https://twitter.com/ericpeters/status/1394315772793483271

Example yaml: https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.yaml

# Use Case

Two possibilities:

1. Like this example, GitHub has a broken YAML file, where some of their API endpoints are complete, others are not.
2. You don't need (or want) a complete client generated for some of these large enterprise REST services.  I don't care about the billing, scim, code-scanning, etc - in this example the API has some tags, or maybe the endpoint prefixes?

```
tags:
- name: actions
  description: Endpoints to manage GitHub Actions using the REST API.
- name: activity
  description: Activity APIs provide access to notifications, subscriptions, and timelines.
- name: apps
  description: Information for integrations and installations.
- name: billing
  description: Monitor charges and usage from Actions and Packages.
- name: checks
  description: Rich interactions with checks run by your integrations.
- name: classroom
  description: Endpoints that give information about Classroom-related data.
- name: code-scanning
  description: Retrieve code scanning alerts from a repository.
- name: codes-of-conduct
  description: Insight into codes of conduct for your communities.
- name: emojis
  description: List emojis available to use on GitHub.
- name: gists
  description: View, modify your gists.
- name: git
  description: Raw Git functionality.
- name: gitignore
  description: View gitignore templates
- name: interactions
  description: Owner or admin management of users interactions.
- name: issues
  description: Interact with GitHub Issues.
- name: licenses
  description: View various OSS licenses.
- name: markdown
  description: Render Github flavored markdown
- name: meta
  description: Endpoints that give information about the API.
- name: migrations
  description: Move projects to or from GitHub.
- name: oauth-authorizations
  description: Manage access of OAuth applications
- name: orgs
  description: Interact with GitHub Orgs.
- name: projects
  description: Interact with GitHub Projects.
- name: pulls
  description: Interact with GitHub Pull Requests.
- name: rate-limit
  description: Check your current rate limit status
- name: reactions
  description: Interact with reactions to various GitHub entities.
- name: repos
  description: Interact with GitHub Repos.
- name: scim
  description: Provisioning of GitHub organization membership for SCIM-enabled providers.
- name: search
  description: Look for stuff on GitHub.
- name: secret-scanning
  description: Retrieve secret scanning alerts from a repository.
- name: teams
  description: Interact with GitHub Teams.
- name: users
  description: Interact with and view information about users and also current user.
```
