### ISSUE TITLE
Generated file fails to compile due to the missing implicit when query parameters contain the parameter named `format`.

### ISSUE THREAD

**Issue by ItoYo16u** [ghostbuster91/sttp-openapi-generator#83]
(I'm not sure here is the place to post this issue. If this issue is related to another project, please tell me the repo.)

-  "org.openapitools" % "sbt-openapi-generator" % "5.0.1"
-  "com.softwaremill.sttp.client" %% "core" % "2.2.0"
-  "com.softwaremill.sttp.client" %% "json4s" % "2.2.0"
-  "org.json4s" %% "json4s-jackson" % "3.6.8"

When I have the parameter named `format`, the code below is generated.
The `format` in argument overrides the implicit value `format` from `import org.openapitools.client.core.JsonSupport._`, which causes compile to fail.

```yaml
paths:
  '/api':
    get:
      parameters:
      - name:  "format"
        in: "query"
        description: "format"
        required: true
        schema:
          type: string
          default: json
```

```scala
package org.openapitools.client.api

import org.openapitools.client.model.SearchResponse
import org.openapitools.client.core.JsonSupport._
import sttp.client._
import sttp.model.Method
class DefaultApi(baseUrl: String) {
  /**
   * 
   * @param format format
   */
  def apiGet(format: String): Request[Either[ResponseError[Exception], MyResponse], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api?format=${ format }")
      .contentType("application/json")
      .response(asJson[MyResponse]) // No org.json4s.Formats found.

}
```
